### ISSUE TITLE
Installation from RPM 

### ISSUE THREAD

**Issue by Forz70043** [wp-cli/builds#58]
installed wp-cli-2.0.1-2.noarch.rpm

if i run `wp`

```
PHP Fatal error:  Uncaught Error: Call to undefined function json_encode() in phar:///usr/bin/wp/vendor/mustache/mustache/src/Mustache/Engine.php:637
Stack trace:
#0 phar:///usr/bin/wp/vendor/mustache/mustache/src/Mustache/Engine.php(729): Mustache_Engine->getTemplateClassName('{{#is_subcomman...')
#1 phar:///usr/bin/wp/vendor/mustache/mustache/src/Mustache/Engine.php(657): Mustache_Engine->loadSource('{{#is_subcomman...')
#2 phar:///usr/bin/wp/vendor/mustache/mustache/src/Mustache/Engine.php(236): Mustache_Engine->loadTemplate('{{#is_subcomman...')
#3 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(492): Mustache_Engine->render('{{#is_subcomman...', Array)
#4 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CompositeCommand.php(304): WP_CLI\Utils\mustache_render('phar://wp-cli.p...', Array)
#5 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CompositeCommand.php(130): WP_CLI\Dispatcher\CompositeCommand->get_global_params()
#6 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcomm in phar:///usr/bin/wp/vendor/mustache/mustache/src/Mustache/Engine.php on line 637

```
Fedora 29
PHP : 5.6 ; 7.2

what i do wrong ?

**Comment by szepeviktor** [comment]
You may miss the JSON extension.

The package may be called `php72-php-json` but I am a Debian-only guy.
